services:
  redis:
    container_name: redis
    restart: always
    image: redis:alpine3.18
    command: /bin/sh -c "touch redis && echo 'requirepass $REDIS_PASSW' >> redis.conf && redis-server redis.conf"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6379:6379