version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:alpine3.18
    ports:
      - "6379:6379"

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:1.14.0
    ports:
      - "8001:8001"

  fastapi:
    container_name: fastapi
    image: ziqix/ebay-balance-fastapi:0.1.0
    ports:
      - "8111:8111"
    depends_on:
      - redis
